# Generated by Django 4.0.6 on 2022-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.ManyToManyField(to='main_app.skill'),
        ),
    ]
